SET FOREIGN_KEY_CHECKS = 0;

INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('1', 'Yes', 'Yes', 'Yes', 'Yes', '3', 'townhome', '123456789', 'Yes', 'free', '8', '12345', '1 Circle Rd', 'Towson', 'MD', '1', '123456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('2', 'Yes', 'Yes', 'No', 'Yes', '2', 'semi-detached', '223456789', 'No', 'free', '7', '22345', '2 Square Dr', 'Baltimore', 'MD', '1', '223456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('3', 'Yes', 'No', 'No', 'Yes', '1', 'single family', '323456789', 'No', 'paid', '4', '32345', '1 Triangle ln', 'Towson', 'MD', '1', '323456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('4', 'Yes', 'No', 'Yes', 'Yes', '5', 'single family', '423456789', 'Yes', 'paid', '10', '52345', '3 Circle Rd', 'Baltimore', 'MD', '1', '423456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('5', 'Yes', 'Yes', 'Yes', 'Yes', '5', 'semi-detached', '533456789', 'Yes', 'free', '9', '42345', '4 Square Dr', 'College Park', 'MD', '1', '523456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('6', 'No', 'Yes', 'Yes', 'Yes', '3', 'townhome', '633456789', 'Yes', 'free', '6', '62345', '5 Circle Rd', 'Baltimore', 'MD', '1', '623456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('7', 'No', 'No', 'No', 'Yes', '3', 'townhome', '733456789', 'Yes', 'free', '7', '72345', '6 Square Dr', 'Baltimore', 'MD', '1', '723456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('8', 'No', 'No', 'No', 'No', '3', 'semi-detached', '833456789', 'No', 'free', '8', '82345', '9 Triangle ln', 'Baltimore', 'MD', '1', '823456789');
INSERT INTO `RealEstate`.`Property` (`propertyID`, `deckOrPatio`, `washer`, `dryer`, `offStreetParking`, `numberOfBaths`, `buildingType`, `phoneNumber`, `basement`, `parkingType`, `numOfRooms`, `zipCode`, `streetAddress`, `city`, `state`, `numOfTennants`, `Tennant_ssn`) VALUES ('9', 'No', 'Yes', 'Yes', 'Yes', '3', 'single family', '933456789', 'Yes', 'free', '7', '92345', '10 Hex St', 'Baltimore', 'MD', '1', '923456789');

SET FOREIGN_KEY_CHECKS = 1;
